version: '3.5'

services:
    polr:
        image: raphox/porl
        container_name: polr
        ports:
            - "8080:8080"
        env_file:
            - .env
        depends_on:
            - mariadb

    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        expose:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - /var/lib/mysql
